// Generated by scripts/generate-country-names.ts — do not edit by hand.
// Regenerate with `pnpm gen:countries`, which is only needed when the locale
// list changes or Node's CLDR data moves. Node v24.0.1 produced this.
//
// Packed as "CODE=Name|CODE=Name" rather than an object literal because it is
// 249 entries per locale: as JSON this file would be several times the
// size, and every byte of it ships to the browser.

import type { AppLocale } from "@/i18n/locales";

/** Every country this site offers, in the order the table was generated. */
export const COUNTRY_CODES: readonly string[] =
	"AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW".split(
		" ",
	);

/** Locale to packed `CODE=Name` pairs. */
export const COUNTRY_NAMES: Record<AppLocale, string> = {
	en:
		"AD=Andorra|AE=United Arab Emirates|AF=Afghanistan|" +
		"AG=Antigua & Barbuda|AI=Anguilla|AL=Albania|AM=Armenia|AO=Angola|" +
		"AQ=Antarctica|AR=Argentina|AS=American Samoa|AT=Austria|" +
		"AU=Australia|AW=Aruba|AX=Åland Islands|AZ=Azerbaijan|" +
		"BA=Bosnia & Herzegovina|BB=Barbados|BD=Bangladesh|BE=Belgium|" +
		"BF=Burkina Faso|BG=Bulgaria|BH=Bahrain|BI=Burundi|BJ=Benin|" +
		"BL=St. Barthélemy|BM=Bermuda|BN=Brunei|BO=Bolivia|" +
		"BQ=Caribbean Netherlands|BR=Brazil|BS=Bahamas|BT=Bhutan|" +
		"BV=Bouvet Island|BW=Botswana|BY=Belarus|BZ=Belize|CA=Canada|" +
		"CC=Cocos (Keeling) Islands|CD=Congo - Kinshasa|" +
		"CF=Central African Republic|CG=Congo - Brazzaville|CH=Switzerland|" +
		"CI=Côte d’Ivoire|CK=Cook Islands|CL=Chile|CM=Cameroon|CN=China|" +
		"CO=Colombia|CR=Costa Rica|CU=Cuba|CV=Cape Verde|CW=Curaçao|" +
		"CX=Christmas Island|CY=Cyprus|CZ=Czechia|DE=Germany|DJ=Djibouti|" +
		"DK=Denmark|DM=Dominica|DO=Dominican Republic|DZ=Algeria|EC=Ecuador|" +
		"EE=Estonia|EG=Egypt|EH=Western Sahara|ER=Eritrea|ES=Spain|" +
		"ET=Ethiopia|FI=Finland|FJ=Fiji|FK=Falkland Islands|FM=Micronesia|" +
		"FO=Faroe Islands|FR=France|GA=Gabon|GB=United Kingdom|GD=Grenada|" +
		"GE=Georgia|GF=French Guiana|GG=Guernsey|GH=Ghana|GI=Gibraltar|" +
		"GL=Greenland|GM=Gambia|GN=Guinea|GP=Guadeloupe|GQ=Equatorial Guinea|" +
		"GR=Greece|GS=South Georgia & South Sandwich Islands|GT=Guatemala|" +
		"GU=Guam|GW=Guinea-Bissau|GY=Guyana|HK=Hong Kong SAR China|" +
		"HM=Heard & McDonald Islands|HN=Honduras|HR=Croatia|HT=Haiti|" +
		"HU=Hungary|ID=Indonesia|IE=Ireland|IL=Israel|IM=Isle of Man|" +
		"IN=India|IO=British Indian Ocean Territory|IQ=Iraq|IR=Iran|" +
		"IS=Iceland|IT=Italy|JE=Jersey|JM=Jamaica|JO=Jordan|JP=Japan|" +
		"KE=Kenya|KG=Kyrgyzstan|KH=Cambodia|KI=Kiribati|KM=Comoros|" +
		"KN=St. Kitts & Nevis|KP=North Korea|KR=South Korea|KW=Kuwait|" +
		"KY=Cayman Islands|KZ=Kazakhstan|LA=Laos|LB=Lebanon|LC=St. Lucia|" +
		"LI=Liechtenstein|LK=Sri Lanka|LR=Liberia|LS=Lesotho|LT=Lithuania|" +
		"LU=Luxembourg|LV=Latvia|LY=Libya|MA=Morocco|MC=Monaco|MD=Moldova|" +
		"ME=Montenegro|MF=St. Martin|MG=Madagascar|MH=Marshall Islands|" +
		"MK=North Macedonia|ML=Mali|MM=Myanmar (Burma)|MN=Mongolia|" +
		"MO=Macao SAR China|MP=Northern Mariana Islands|MQ=Martinique|" +
		"MR=Mauritania|MS=Montserrat|MT=Malta|MU=Mauritius|MV=Maldives|" +
		"MW=Malawi|MX=Mexico|MY=Malaysia|MZ=Mozambique|NA=Namibia|" +
		"NC=New Caledonia|NE=Niger|NF=Norfolk Island|NG=Nigeria|NI=Nicaragua|" +
		"NL=Netherlands|NO=Norway|NP=Nepal|NR=Nauru|NU=Niue|NZ=New Zealand|" +
		"OM=Oman|PA=Panama|PE=Peru|PF=French Polynesia|PG=Papua New Guinea|" +
		"PH=Philippines|PK=Pakistan|PL=Poland|PM=St. Pierre & Miquelon|" +
		"PN=Pitcairn Islands|PR=Puerto Rico|PS=Palestinian Territories|" +
		"PT=Portugal|PW=Palau|PY=Paraguay|QA=Qatar|RE=Réunion|RO=Romania|" +
		"RS=Serbia|RU=Russia|RW=Rwanda|SA=Saudi Arabia|SB=Solomon Islands|" +
		"SC=Seychelles|SD=Sudan|SE=Sweden|SG=Singapore|SH=St. Helena|" +
		"SI=Slovenia|SJ=Svalbard & Jan Mayen|SK=Slovakia|SL=Sierra Leone|" +
		"SM=San Marino|SN=Senegal|SO=Somalia|SR=Suriname|SS=South Sudan|" +
		"ST=São Tomé & Príncipe|SV=El Salvador|SX=Sint Maarten|SY=Syria|" +
		"SZ=Eswatini|TC=Turks & Caicos Islands|TD=Chad|" +
		"TF=French Southern Territories|TG=Togo|TH=Thailand|TJ=Tajikistan|" +
		"TK=Tokelau|TL=Timor-Leste|TM=Turkmenistan|TN=Tunisia|TO=Tonga|" +
		"TR=Türkiye|TT=Trinidad & Tobago|TV=Tuvalu|TW=Taiwan|TZ=Tanzania|" +
		"UA=Ukraine|UG=Uganda|UM=U.S. Outlying Islands|US=United States|" +
		"UY=Uruguay|UZ=Uzbekistan|VA=Vatican City|" +
		"VC=St. Vincent & Grenadines|VE=Venezuela|VG=British Virgin Islands|" +
		"VI=U.S. Virgin Islands|VN=Vietnam|VU=Vanuatu|WF=Wallis & Futuna|" +
		"WS=Samoa|YE=Yemen|YT=Mayotte|ZA=South Africa|ZM=Zambia|ZW=Zimbabwe",
	ro:
		"AD=Andorra|AE=Emiratele Arabe Unite|AF=Afganistan|" +
		"AG=Antigua și Barbuda|AI=Anguilla|AL=Albania|AM=Armenia|AO=Angola|" +
		"AQ=Antarctica|AR=Argentina|AS=Samoa Americană|AT=Austria|" +
		"AU=Australia|AW=Aruba|AX=Insulele Åland|AZ=Azerbaidjan|" +
		"BA=Bosnia și Herțegovina|BB=Barbados|BD=Bangladesh|BE=Belgia|" +
		"BF=Burkina Faso|BG=Bulgaria|BH=Bahrain|BI=Burundi|BJ=Benin|" +
		"BL=Saint-Barthélemy|BM=Bermuda|BN=Brunei|BO=Bolivia|" +
		"BQ=Insulele Caraibe Olandeze|BR=Brazilia|BS=Bahamas|BT=Bhutan|" +
		"BV=Insula Bouvet|BW=Botswana|BY=Belarus|BZ=Belize|CA=Canada|" +
		"CC=Insulele Cocos (Keeling)|CD=Congo - Kinshasa|" +
		"CF=Republica Centrafricană|CG=Congo - Brazzaville|CH=Elveția|" +
		"CI=Côte d’Ivoire|CK=Insulele Cook|CL=Chile|CM=Camerun|CN=China|" +
		"CO=Columbia|CR=Costa Rica|CU=Cuba|CV=Capul Verde|CW=Curaçao|" +
		"CX=Insula Christmas|CY=Cipru|CZ=Cehia|DE=Germania|DJ=Djibouti|" +
		"DK=Danemarca|DM=Dominica|DO=Republica Dominicană|DZ=Algeria|" +
		"EC=Ecuador|EE=Estonia|EG=Egipt|EH=Sahara Occidentală|ER=Eritreea|" +
		"ES=Spania|ET=Etiopia|FI=Finlanda|FJ=Fiji|FK=Insulele Falkland|" +
		"FM=Micronezia|FO=Insulele Feroe|FR=Franța|GA=Gabon|GB=Regatul Unit|" +
		"GD=Grenada|GE=Georgia|GF=Guyana Franceză|GG=Guernsey|GH=Ghana|" +
		"GI=Gibraltar|GL=Groenlanda|GM=Gambia|GN=Guineea|GP=Guadelupa|" +
		"GQ=Guineea Ecuatorială|GR=Grecia|" +
		"GS=Georgia de Sud și Insulele Sandwich de Sud|GT=Guatemala|GU=Guam|" +
		"GW=Guineea-Bissau|GY=Guyana|HK=R.A.S. Hong Kong, China|" +
		"HM=Insula Heard și Insulele McDonald|HN=Honduras|HR=Croația|" +
		"HT=Haiti|HU=Ungaria|ID=Indonezia|IE=Irlanda|IL=Israel|IM=Insula Man|" +
		"IN=India|IO=Teritoriul Britanic din Oceanul Indian|IQ=Irak|IR=Iran|" +
		"IS=Islanda|IT=Italia|JE=Jersey|JM=Jamaica|JO=Iordania|JP=Japonia|" +
		"KE=Kenya|KG=Kârgâzstan|KH=Cambodgia|KI=Kiribati|KM=Comore|" +
		"KN=Saint Kitts și Nevis|KP=Coreea de Nord|KR=Coreea de Sud|" +
		"KW=Kuweit|KY=Insulele Cayman|KZ=Kazahstan|LA=Laos|LB=Liban|" +
		"LC=Sfânta Lucia|LI=Liechtenstein|LK=Sri Lanka|LR=Liberia|LS=Lesotho|" +
		"LT=Lituania|LU=Luxemburg|LV=Letonia|LY=Libia|MA=Maroc|MC=Monaco|" +
		"MD=Republica Moldova|ME=Muntenegru|MF=Sfântul Martin|MG=Madagascar|" +
		"MH=Insulele Marshall|MK=Macedonia de Nord|ML=Mali|" +
		"MM=Myanmar (Birmania)|MN=Mongolia|MO=R.A.S. Macao, China|" +
		"MP=Insulele Mariane de Nord|MQ=Martinica|MR=Mauritania|" +
		"MS=Montserrat|MT=Malta|MU=Mauritius|MV=Maldive|MW=Malawi|MX=Mexic|" +
		"MY=Malaysia|MZ=Mozambic|NA=Namibia|NC=Noua Caledonie|NE=Niger|" +
		"NF=Insula Norfolk|NG=Nigeria|NI=Nicaragua|NL=Țările de Jos|" +
		"NO=Norvegia|NP=Nepal|NR=Nauru|NU=Niue|NZ=Noua Zeelandă|OM=Oman|" +
		"PA=Panama|PE=Peru|PF=Polinezia Franceză|PG=Papua-Noua Guinee|" +
		"PH=Filipine|PK=Pakistan|PL=Polonia|PM=Saint-Pierre și Miquelon|" +
		"PN=Insulele Pitcairn|PR=Puerto Rico|PS=Teritoriile Palestiniene|" +
		"PT=Portugalia|PW=Palau|PY=Paraguay|QA=Qatar|RE=Réunion|RO=România|" +
		"RS=Serbia|RU=Rusia|RW=Rwanda|SA=Arabia Saudită|SB=Insulele Solomon|" +
		"SC=Seychelles|SD=Sudan|SE=Suedia|SG=Singapore|SH=Sfânta Elena|" +
		"SI=Slovenia|SJ=Svalbard și Jan Mayen|SK=Slovacia|SL=Sierra Leone|" +
		"SM=San Marino|SN=Senegal|SO=Somalia|SR=Suriname|SS=Sudanul de Sud|" +
		"ST=São Tomé și Príncipe|SV=El Salvador|SX=Sint-Maarten|SY=Siria|" +
		"SZ=Eswatini|TC=Insulele Turks și Caicos|TD=Ciad|" +
		"TF=Teritoriile Australe și Antarctice Franceze|TG=Togo|TH=Thailanda|" +
		"TJ=Tadjikistan|TK=Tokelau|TL=Timor-Leste|TM=Turkmenistan|TN=Tunisia|" +
		"TO=Tonga|TR=Turcia|TT=Trinidad și Tobago|TV=Tuvalu|TW=Taiwan|" +
		"TZ=Tanzania|UA=Ucraina|UG=Uganda|UM=Insulele Îndepărtate ale S.U.A.|" +
		"US=Statele Unite ale Americii|UY=Uruguay|UZ=Uzbekistan|" +
		"VA=Statul Cetății Vaticanului|VC=Saint Vincent și Grenadinele|" +
		"VE=Venezuela|VG=Insulele Virgine Britanice|" +
		"VI=Insulele Virgine Americane|VN=Vietnam|VU=Vanuatu|" +
		"WF=Wallis și Futuna|WS=Samoa|YE=Yemen|YT=Mayotte|ZA=Africa de Sud|" +
		"ZM=Zambia|ZW=Zimbabwe",
};
