/**
 * Regenerates `src/lib/country-names.ts`.
 *
 *   pnpm gen:countries
 *
 * Country names are a generated table rather than a runtime `Intl.DisplayNames`
 * lookup, and the reason is worth keeping in mind before anyone "simplifies" it
 * back: display names come from whichever CLDR version the *runtime* was built
 * against, so Node and the browser disagree — measured, on this pair, for FK,
 * HK, MO and PS. A country name rendered by a client component would then be a
 * hydration mismatch waiting for somebody from Hong Kong to sign up.
 *
 * Generating every locale here, from one Node, keeps the whole table on a
 * single CLDR version — which is also the answer to the objection that a second
 * language means maintaining a matrix by hand. Nobody maintains it. It is
 * regenerated wholesale, and only when the locale list or Node changes.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { LOCALES } from "../src/i18n/locales";

/**
 * ISO 3166-1 alpha-2, the subset this site offers. Deliberately a literal list
 * rather than anything derived: it is the set of flags `flag-icons` ships, and
 * a country with no flag renders as an empty box.
 */
const CODES =
	"AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW".split(
		" ",
	);

/** Wrap a long packed string into source lines that read at a glance. */
function wrap(packed: string, width = 68): string {
	const lines: string[] = [];
	let line = "";

	for (const pair of packed.split("|")) {
		const next = line ? `${line}${pair}|` : `${pair}|`;
		if (next.length > width && line) {
			lines.push(line);
			line = `${pair}|`;
		} else {
			line = next;
		}
	}
	if (line) lines.push(line);

	// The final pair carries no separator.
	const last = lines[lines.length - 1];
	if (last?.endsWith("|")) lines[lines.length - 1] = last.slice(0, -1);

	return lines.map((value) => `\t\t\t"${value}"`).join(" +\n");
}

const blocks = LOCALES.map((locale) => {
	const display = new Intl.DisplayNames([locale], { type: "region" });

	const packed = CODES.map((code) => {
		const name = display.of(code);
		if (!name || name === code) {
			throw new Error(`No ${locale} name for ${code} — check the Node version`);
		}
		// `=` and `|` are the separators; a name containing either would corrupt
		// the table silently, so fail loudly instead.
		if (name.includes("=") || name.includes("|")) {
			throw new Error(
				`${locale} name for ${code} contains a separator: ${name}`,
			);
		}
		return `${code}=${name}`;
	}).join("|");

	return `\t${locale}:\n${wrap(packed)},`;
}).join("\n");

const file = `// Generated by scripts/generate-country-names.ts — do not edit by hand.
// Regenerate with \`pnpm gen:countries\`, which is only needed when the locale
// list changes or Node's CLDR data moves. Node ${process.version} produced this.
//
// Packed as "CODE=Name|CODE=Name" rather than an object literal because it is
// ${CODES.length} entries per locale: as JSON this file would be several times the
// size, and every byte of it ships to the browser.

import type { AppLocale } from "@/i18n/locales";

/** Every country this site offers, in the order the table was generated. */
export const COUNTRY_CODES: readonly string[] = ${JSON.stringify(CODES.join(" "))}.split(" ");

/** Locale to packed \`CODE=Name\` pairs. */
export const COUNTRY_NAMES: Record<AppLocale, string> = {
${blocks}
};
`;

const out = join(process.cwd(), "src", "lib", "country-names.ts");
writeFileSync(out, file, "utf8");

console.log(
	`src/lib/country-names.ts — ${CODES.length} countries x ${LOCALES.length} locales (${LOCALES.join(", ")}), from Node ${process.version}`,
);
