/**
 * Regenerates `public/icon.svg`.
 *
 *   pnpm gen:icon
 *
 * The mark exists three times over — as JSX in `Brand`, as shapes in the Open
 * Graph card, and as a standalone file that the web manifest and every "add to
 * home screen" reads. The first two share `src/lib/brand-mark`; this one cannot,
 * because a manifest icon has to be a URL to a real file that a browser fetches
 * without running any of our code.
 *
 * So it is generated from the same shapes rather than drawn a second time. Run
 * this after touching the artwork; there is no build step that will notice for
 * you, which is the trade for the file being static and cacheable.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { MARK_HEIGHT, MARK_SHAPES, MARK_WIDTH } from "../src/lib/brand-mark";

/**
 * The artwork is a tall pawn; an icon is a square. Centring it in a square
 * viewBox with room around it is what stops the piece being cropped to a stripe
 * by every launcher that masks icons into a circle — the safe zone is the
 * middle 80%, so the piece is inset by a tenth on the tall axis.
 */
const PAD = MARK_HEIGHT * 0.125;
const SIZE = MARK_HEIGHT + PAD * 2;
const OFFSET_X = (SIZE - MARK_WIDTH) / 2;

function shapeToSvg(shape: (typeof MARK_SHAPES)[number]): string {
	switch (shape.kind) {
		case "rect":
			return `<rect x="${shape.x}" y="${shape.y}" width="${shape.width}" height="${shape.height}" rx="${shape.rx}" fill="${shape.fill}"/>`;
		case "circle":
			return `<circle cx="${shape.cx}" cy="${shape.cy}" r="${shape.r}" fill="${shape.fill}"/>`;
		default:
			return `<path d="${shape.d}" fill="${shape.fill}"/>`;
	}
}

const svg = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-icon.ts — do not edit. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}" width="${SIZE}" height="${SIZE}" role="img" aria-label="Esahist.ro">
  <g transform="translate(${OFFSET_X} ${PAD})">
${MARK_SHAPES.map((shape) => `    ${shapeToSvg(shape)}`).join("\n")}
  </g>
</svg>
`;

const out = join(import.meta.dirname, "..", "public", "icon.svg");
writeFileSync(out, svg, "utf8");
console.log(`wrote ${out}`);
